### ISSUE TITLE
index.html - update text in Registration

### ISSUE THREAD

**Issue by hellolulu** [ibcol/XBCOL-HK-2023#11]
Change Registration header to How to Join.

Everyone can apply for the Hong Kong Blockchain Olympiad. 

Change Button text from 'Register' to 'Find out more'. Find out more should link to (TBC, may be apply for passport page?).

**Comment by hellolulu** [comment]
Suggest link to be 'Submit Project' under 'How to Join'

**Comment by louiselokyi** [comment]
> Suggest link to be 'Submit Project' under 'How to Join'

@hellolulu Sorry, I don't quite get this, would you mind explaining more?
