### ISSUE TITLE
Update special event tab - hover to a drop down list for these 3 categories - Exam, GBA IBCOL, Amsterdam IBCOL 

### ISSUE THREAD

**Issue by hellolulu** [ibcol/XBCOL-HK-2023#15]
Please refer to the latest site map for reference.
https://www.figma.com/file/IpTFhWn1MNw866n97EIPQG/Site-Map-for-HK%2FMO%2FCN-IBCOL-sites?node-id=0%3A1&t=TSXaloWcQ4DRQY3U-1

**Comment by k-deepak04** [comment]
#19 fixed the issue
![Uploading Screenshot 2023-04-17 204248.png…]()
