### ISSUE TITLE
Clarity on "Team Profile" (Rules > Secondary > Submission of Specifications)

### ISSUE THREAD

**Issue by ninjapanda** [ibcol/XBCOL-HK-2023#42]
**Problem:** the team profile details are not specified.

**Solution:** specify that this is only for Round 3 and also provide an example document and let them know that this should be uploaded in their public cloud storage link

**Comment by hellolulu** [comment]
1. Remove Note at the bottom of the page.
Note: 
- If your country or territory has a Competition Committee, please refer to the submission timeline as outlined by the committee; the materials may be required in one submission or in separate submissions.
- If your country or territory does not have a Competition Committee, please submit the survey, video and poster in one batch directly to the IBCOL Committee via the [[website](https://2023.ibcol.org/submission.html)](https://2023.ibcol.org/submission.html).

2. Add Rounds and Deadlines for each material submission (refer to Notion > HKBCOL 2023: Website Structure & Content > Rules > Secondary > Specification of Submissions.) 

3. Remove first sentence 'The material submission requires the following items: team profile, survey, video and poster.' and change to 'There will be 3 rounds of submission. Please note that only qualified submissions will proceed to the next round of submission.' (refer to Notion > HKBCOL 2023: Website Structure & Content > Rules > Secondary > Specification of Submissions.)

4. Team profile is missing as a material submission specification. Please be sure to add this as part of round 3 submission for secondary track. Thank you.
