### ISSUE TITLE
home page - update introduction text

### ISSUE THREAD

**Issue by hellolulu** [ibcol/XBCOL-HK-2023#5]
Please replace the current introduction to the below: 

The Hong Kong Blockchain Olympiad (HKBCOL) is an annual competition inviting current and recent students to propose solutions to real-world problems using blockchain technology.

HKBCOL combines the practicality of a traditional case competitions with the open-ended problem-solving culture of hack-a-thons. As a team of up to 6 students, competitors will submit their case as using an academic conference style white-paper along with a 3-min video presentation and a poster board.

High performing teams are then invited to register for the International Blockchain Olympiad where they compete against the very best from around the world.

No registration or participation costs.

**Comment by ninjapanda** [comment]
Please mention which page(s) to edit

**Comment by hellolulu** [comment]
@ninjapanda Sorry, please replace the text in XBCOL-HK-2023/index.html and XBCOL-HK-2023/about.html

**Comment by ninjapanda** [comment]
index.html has been replaced with even shorter text

about.html should be amended with these changes :)
