### ISSUE TITLE
index.html - update text in Why Join

### ISSUE THREAD

**Issue by hellolulu** [ibcol/XBCOL-HK-2023#6]
Replace the current text with the following under Why Join? 

Future-proof Skills for Self and Society
Future-proof your skills and gain valuable experience in a field that is poised to grow rapidly in the coming years. Showcase your knowledge and abilities, network with industry experts and professionals, and stay up-to-date with the latest developments and best practices in the industry. 

Certifications
Come present and exchange ideas, and potentially gain recognition for your work! 8 teams will be shortlisted to represent Hong Kong and be guaranteed a place in the finals in Amsterdam. Top 3 will be presented with Gold, Silver and Bronze Medals. Distinction awards will be given to those who demonstrate exceptional knowledge and skills in blockchain technology, and merit awards will be given to those who show promise and potential in the field. 

Gain Exposure
Learn about the wide range of blockchain projects and applications at the Greater Bay Area Blockchain Olympiad, where teams from Hong Kong, Macau and China exhibit their work and share ideas.

**Comment by k-deepak04** [comment]
@hellolulu i want to contribute.
the mentioned text should be written in paragraph or li ?

**Comment by k-deepak04** [comment]
Updated text
![Screenshot (193)](https://user-images.githubusercontent.com/96341431/232523282-51fef2f2-9519-4bef-a849-e5bbe6ab9fbb.png)
