### ISSUE TITLE
index.html - change text in Workshops

### ISSUE THREAD

**Issue by hellolulu** [ibcol/XBCOL-HK-2023#7]
Please replace the current with the text below:  
Join courses to learn blockchain as a technology from the fundamentals. Courses are sponsored by Innovation and Technology Commission (ITC). Find out more in the link below.

**Comment by k-deepak04** [comment]
Changed the text.
Kindly review it and merge. 
![image](https://user-images.githubusercontent.com/96341431/232524509-3d083d6e-4f41-44b1-b8a1-20b040b8ac0c.png)
